
directions = {
    'Backend': {
        'attachment': True,
        'group': [
            'Python',
            'Java',
            'PHP',
            'Node.js',
            'C/C++',
            'C#',
            '1C',
            'Golang',
            'Ruby',
            'Rust'
        ]
    },
    'Frontend': {
        'attachment': True,
        'group': [
            'React',
            'Vue',
            'Angular',
            'HTML/CSS',
        ],
    },
    'Мобил. разработка': {
        'attachment': True,
        'group': [
            'Flutter',
            'Kotlin',
            'Swift',
        ],
    },
    'GameDev': {
        'attachment': True,
        'group': [
            'Unity',
            'Unreal Engine',
        ],
    },
    'DS и Аналитика': {
        'attachment': True,
        'group': [
            'Machin Learning',
            'Data Engineer',
            'Product Analyst',
            'Data Analyst',
            'System Analyst',
            'Business Analyst',
        ],
    },
    'Тестирование': {
        'attachment': True,
        'group': [
            'Auto(Python)',
            'Auto(Java)',
            'Ручное',
        ],
    },
    'Менеджмент': {
        'attachment': True,
        'group': [
            'Product Manager',
            'Project Manager',
            'HR',
        ],
    },
    'Дизайн': {
        'attachment': True,
        'group': [
            'Product Designer',
            'UX/UI Designer',
        ],
    },
    'Админ-вание': {
        'attachment': True,
        'group': [
            'Devops',
            'System Admin',
            'Database Admin',
            'Network Engineer',
        ],
    },
}

channels_groups = {
    'Python': [
        ['Backend', 'easy_backend'],
        ['Python | Вопросы собесов', 'python_easy_ru'],
        ['Python | Classroom', 'easy_python_memes'],
        ['Python | Удалёнка', 'easy_python_job'],
        ['Python | Задачи', 'easy_python_task'],
        ['Python | Тестовые задания', 'easy_python_tests'],
        ['English for IT', 'easy_english_for_it'],
    ],
    'PHP': [
        ['Backend', 'easy_backend'],
        ['PHP | Вопросы собесов', 'easy_php_ru'],
        ['PHP | Удалёнка', 'easy_php_job'],
        ['PHP | Задачи', 'easy_php_task'],
        ['PHP | Тестовые задания', 'easy_php_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Node.js': [
        ['Backend', 'easy_backend'],
        ['Node.js', 'easy_node_js'],
        ['Node.js | Удалёнка', 'easy_node_js_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Java': [
        ['Backend', 'easy_backend'],
        ['Java | Вопросы собесов', 'easy_java_ru'],
        ['Java | Classroom', 'easy_java_memes'],
        ['Java | Удалёнка', 'easy_java_job'],
        ['Java | Задачи', 'easy_java_task'],
        ['Java | Тестовые задания', 'easy_java_tests'],
        ['English for IT', 'easy_english_for_it'],
    ],
    'C/C++': [
        ['Backend', 'easy_backend'],
        ['C/C++ | Вопросы собесов', 'easy_c_plus'],
        ['C/C++ | Удалёнка', 'easy_cplus_job'],
        ['C/C++ | Задачи', 'easy_c_plus_task'],
        ['C/C++ | Тестовые задания', 'easy_c_plus_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Golang': [
        ['Backend', 'easy_backend'],
        ['Golang | Вопросы собесов', 'easy_golang'],
        ['Golang | Удалёнка', 'easy_golang_job'],
        ['Golang | Задачи', 'easy_golang_task'],
        ['Golang | Тестовые задания', 'easy_golang_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Ruby': [
        ['Backend', 'easy_backend'],
        ['Ruby', 'easy_ruby'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Rust': [
        ['Backend', 'easy_backend'],
        ['Rust', 'easy_rust_ru'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    '1C': [
        ['Backend', 'easy_backend'],
        ['1C', 'ru_1c_easy'],
        ['1C | Удалёнка', 'easy_1c_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'C#': [
        ['Backend', 'easy_backend'],
        ['C# | Вопросы собесов', 'easy_c_sharp'],
        ['C# | Удалёнка', 'easy_csharp_job'],
        ['C# | Задачи', 'easy_c_sharp_task'],
        ['C# | Тестовые задания', 'easy_c_sharp_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'React': [
        ['Frontend | Вопросы собесов', 'easy_javascript_ru'],
        ['Frontend | Classroom', 'easy_frontend_memes'],
        ['Frontend | Удалёнка', 'easy_frontend_jobs'],
        ['Frontend | Задачи', 'easy_frontend_task'],
        ['Frontend | Тестовые задания', 'easy_frontend_tests'],
        ['English for IT', 'easy_english_for_it'],
    ],
    'Vue': [
        ['Frontend | Вопросы собесов', 'easy_javascript_ru'],
        ['Frontend | Classroom', 'easy_frontend_memes'],
        ['Frontend | Удалёнка', 'easy_frontend_jobs'],
        ['Frontend | Задачи', 'easy_frontend_task'],
        ['Frontend | Тестовые задания', 'easy_frontend_tests'],
        ['English for IT', 'easy_english_for_it'],
    ],
    'Angular': [
        ['Frontend | Вопросы собесов', 'easy_javascript_ru'],
        ['Frontend | Classroom', 'easy_frontend_memes'],
        ['Frontend | Удалёнка', 'easy_frontend_jobs'],
        ['Frontend | Задачи', 'easy_frontend_task'],
        ['Frontend | Тестовые задания', 'easy_frontend_tests'],
        ['English for IT', 'easy_english_for_it'],
    ],
    'HTML/CSS': [
        ['Frontend | Вопросы собесов', 'easy_javascript_ru'],
        ['Frontend | Classroom', 'easy_frontend_memes'],
        ['Frontend | Удалёнка', 'easy_frontend_jobs'],
        ['Frontend | Задачи', 'easy_frontend_task'],
        ['Frontend | Тестовые задания', 'easy_frontend_tests'],
        ['English for IT', 'easy_english_for_it'],
    ],
    'Flutter': [
        ['Flutter | Вопросы собесов', 'easy_flutter_ru'],
        ['Futter | Удалёнка', 'easy_flutter_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Kotlin': [
        ['Kotlin | Вопросы собесов', 'easy_kotlin'],
        ['Kotlin | Удалёнка', 'easy_kotlin_job'],
        ['Kotlin | Задачи', 'easy_kotlin_task'],
        ['Kotlin | Тестовые задания', 'easy_kotlin_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Swift': [
        ['Swift | Вопросы собесов', 'easy_swift'],
        ['Swift | Удалёнка', 'easy_swift_job'],
        ['Swift | Задачи', 'easy_swift_task'],
        ['Swift | Тестовые задания', 'easy_swift_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Unity': [
        ['Unity', 'easy_unity_ru'],
        ['Unity | Удалёнка', 'easy_unity_job'],
        ['C#', 'easy_c_sharp'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Unreal Engine': [
        ['Unreal Engine', 'easy_unreal_engine'],
        ['Unreal Engine | Удалёнка', 'easy_unreal_job'],
        ['C/C++', 'easy_c_plus'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Machin Learning': [
        ['Data Science | Вопросы собесов', 'easy_ds'],
        ['Data Science | Удалёнка', 'easy_ds_job'],
        ['Data Science | Задачи', 'easy_ds_task'],
        ['Data Science | Тестовые задания', 'easy_ds_tests'],
        ['Machin Learning', 'easy_machin_learning'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Data Engineer': [
        ['Data Science | Вопросы собесов', 'easy_ds'],
        ['Data Science | Удалёнка', 'easy_ds_job'],
        ['Data Science | Задачи', 'easy_ds_task'],
        ['Data Science | Тестовые задания', 'easy_ds_tests'],
        ['Data Engineer', 'easy_data_engineer'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Product Analyst': [
        ['Data Science | Вопросы собесов', 'easy_ds'],
        ['Data Science | Удалёнка', 'easy_ds_job'],
        ['Data Science | Задачи', 'easy_ds_task'],
        ['Data Science | Тестовые задания', 'easy_ds_tests'],
        ['Product Analyst', 'easy_product_analyst'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Data Analyst': [
        ['Data Science | Вопросы собесов', 'easy_ds'],
        ['Data Science | Удалёнка', 'easy_ds_job'],
        ['Data Science | Задачи', 'easy_ds_task'],
        ['Data Science | Тестовые задания', 'easy_ds_tests'],
        ['Data Analyst', 'easy_data_analyst'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'System Analyst': [
        ['System Analyst', 'easy_system_analyst'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Business Analyst': [
        ['Business Analyst', 'easy_business_analyst_ru'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Auto(Python)': [
        ['Тестировщик | Вопросы собесов', 'easy_qa_ru'],
        ['Тестировщик | Удалёнка', 'easy_qa_jobs'],
        ['Тестировщик | Задачи', 'easy_qa_task'],
        ['Тестировщик | Тестовые задания', 'easy_qa_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Auto(Java)': [
        ['Тестировщик | Вопросы собесов', 'easy_qa_ru'],
        ['Тестировщик | Удалёнка', 'easy_qa_jobs'],
        ['Тестировщик | Задачи', 'easy_qa_task'],
        ['Тестировщик | Тестовые задания', 'easy_qa_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Ручное': [
        ['Тестировщик | Вопросы собесов', 'easy_qa_ru'],
        ['Тестировщик | Удалёнка', 'easy_qa_jobs'],
        ['Тестировщик | Задачи', 'easy_qa_task'],
        ['Тестировщик | Тестовые задания', 'easy_qa_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Product Manager': [
        ['Product Manager', 'easy_product_manager'],
        ['Product Manager | Удалёнка', 'easy_product_m_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Project Manager': [
        ['Project Manager', 'easy_project_manager'],
        ['Project Manager | Удалёнка', 'easy_project_m_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Product Designer': [
        ['Product Designer', 'easy_product_designer'],
        ['Product Designer | Удалёнка', 'easy_product_designer_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'UX/UI Designer': [
        ['UX/UI Designer', 'easy_UX_UI'],
        ['UX/UI Designer | Удалёнка', 'easy_ux_ui_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'HR': [
        ['HR', 'easy_human_resources'],
        ['HR | Удалёнка', 'easy_hr_job'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Devops': [
        ['DevOps | Вопросы собесов', 'easy_devops'],
        ['DevOps | Удалёнка', 'easy_devops_job'],
        ['DevOps | Задачи', 'easy_devops_task'],
        ['DevOps | Тестовые задания', 'easy_devops_tests'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'System Admin': [
        ['System Admin', 'easy_system_admin'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Database Admin': [
        ['Database Admin', 'easy_database_admin'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
    'Network Engineer': [
        ['Network Engineer', 'easy_network_engineer'],
        ['English for IT', 'easy_english_for_it'],
        ['IT Мемес', 'easy_it_memes'],
    ],
}
